//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtelRezervasyonSistemi.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblKasa
    {
        public int KasaID { get; set; }
        public string KasaAdi { get; set; }
        public Nullable<decimal> KasaBakiye { get; set; }
        public Nullable<decimal> KasaGiren { get; set; }
        public Nullable<decimal> KasaCikan { get; set; }
        public Nullable<int> KasaDurum { get; set; }
    
        public virtual TblDurum TblDurum { get; set; }
    }
}
