//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtelRezervasyonSistemi.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblKur
    {
        public int KurID { get; set; }
        public string KurAd { get; set; }
        public string KurSembol { get; set; }
        public Nullable<decimal> KurDeger { get; set; }
        public Nullable<System.DateTime> KurTarih { get; set; }
        public Nullable<int> KurDurum { get; set; }
    }
}
