//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtelRezervasyonSistemi.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblMusteri
    {
        public int MusteriID { get; set; }
        public string MusteriAdSoyad { get; set; }
        public string MusteriTC { get; set; }
        public string MusteriMail { get; set; }
        public string MusteriTelefon { get; set; }
        public string MusteriAdres { get; set; }
        public string MusteriAciklama { get; set; }
        public string MusteriKimlikFoto1 { get; set; }
        public string MusteriKimlikFoto2 { get; set; }
        public Nullable<int> MusteriUlke { get; set; }
        public Nullable<int> MusteriDurum { get; set; }
        public Nullable<int> MusteriSehir { get; set; }
        public Nullable<int> MusteriIlce { get; set; }
    
        public virtual TblDurum TblDurum { get; set; }
        public virtual TblIlceler TblIlceler { get; set; }
        public virtual TblSehirler TblSehirler { get; set; }
    }
}
