//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtelRezervasyonSistemi.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblOda
    {
        public int OdaID { get; set; }
        public string OdaNo { get; set; }
        public string OdaKat { get; set; }
        public string OdaKapasite { get; set; }
        public string OdaAciklama { get; set; }
        public string OdaTelefon { get; set; }
        public Nullable<int> OdaDurum { get; set; }
    
        public virtual TblDurum TblDurum { get; set; }
    }
}
