//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtelRezervasyonSistemi.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblPersonel
    {
        public int PersonelID { get; set; }
        public string PersonelAdSoyad { get; set; }
        public string PersonelTC { get; set; }
        public string PersonelAdres { get; set; }
        public string PersonelTelefon { get; set; }
        public string PersonelMail { get; set; }
        public Nullable<System.DateTime> PersonelIseGirisTarihi { get; set; }
        public Nullable<System.DateTime> PersonelIstenCikisTarihi { get; set; }
        public Nullable<int> PersonelDepartman { get; set; }
        public Nullable<int> PersonelGorev { get; set; }
        public string PersonelAciklama { get; set; }
        public Nullable<int> PersonelDurum { get; set; }
    
        public virtual TblDepartman TblDepartman { get; set; }
        public virtual TblDurum TblDurum { get; set; }
        public virtual TblGorev TblGorev { get; set; }
    }
}
